server:
  port: 8080
  servlet:
    context-path: /cxj
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/store?characterEncoding=utf8
    username: root
    password: admin
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计，"wall"用于防火墙
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true

logging:
  file:
    name: ../logs/cxj.log